services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      - APACHE_DOMAIN=localhost
      - APACHE_PORT=80
      - DATABASE_URL=mysql://root:rootpassword@db:3306/app_db
      - DISABLE_SSL=true
    volumes:
      - .:/var/www/html
      - /tmp:/tmp
      - /var/log:/var/log
