version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:10000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8080
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=ujem_db
      - DB_USERNAME=ujem_user
      - DB_PASSWORD=ujem_password
    depends_on:
      - db
    volumes:
      - .:/var/www/html
      - ./storage/logs:/var/www/html/storage/logs
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=ujem_db
      - POSTGRES_USER=ujem_user
      - POSTGRES_PASSWORD=ujem_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
