version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8080
      - DB_CONNECTION=mysql
      - DB_HOST=yamanote.proxy.rlwy.net
      - DB_PORT=58372
      - DB_DATABASE=railway
      - DB_USERNAME=root
      - DB_PASSWORD=lHrCOmGSvbbiTSntPYLwjlWMuthCRxNu
    volumes:
      - .:/var/www/html
      - ./storage/logs:/var/log/apache2
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Uncomment if you want to use a local database instead
    # depends_on:
    #   - db

  # Uncomment if you want to use a local database instead
  # db:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     MYSQL_DATABASE: railway
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: lHrCOmGSvbbiTSntPYLwjlWMuthCRxNu
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   restart: unless-stopped

# volumes:
#   mysql_data:
