services:
  - type: web
    name: ujem-php
    env: php
    buildCommand: "composer install --no-dev"
    startCommand: "php -S 0.0.0.0:10000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://votre-nom-app.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: ujem-db
          property: connection.host
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        fromDatabase:
          name: ujem-db
          property: connection.database
      - key: DB_USERNAME
        fromDatabase:
          name: ujem-db
          property: connection.username
      - key: DB_PASSWORD
        fromDatabase:
          name: ujem-db
          property: connection.password
    plan: free
    numInstances: 1