services:
  - type: web
    name: ujem-app
    env: docker
    dockerfile: Dockerfile
    buildCommand: ""
    startCommand: "/usr/local/bin/start.sh"
    plan: free
    numInstances: 1
    envVars:
      - key: PORT
        value: 10000
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://ujem-app.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: ujem-db
          property: hostname
      - key: DB_PORT
        fromDatabase:
          name: ujem-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: ujem-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: ujem-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ujem-db
          property: password
